#!/bin/bash

# heavily modified from the original script at
# https://spaceli.wordpress.com/2014/07/23/latexmk-gvim-sumatrapdf-wine-on-linux/
# usage: conv_synctex_wine <program> <arguments> ...

MAINFILE=${!#%.*}
ARGS=("$@")
"${ARGS[@]}"


mv "${MAINFILE}.synctex.gz" "${MAINFILE}.synctex.orig.gz"
gzip -c -d "${MAINFILE}.synctex.orig.gz" | sed -e '/^Input/s_/_\\_g' -e '/^Input/s_:\\_:Z:\\_' | gzip > "${MAINFILE}.synctex.gz"
rm "${MAINFILE}.synctex.orig.gz"
